class Rate < ApplicationRecord


  RATE_ATTRIBUTES = %w["contract_id"	"lane_calc"	"from_loccode"	"from_city"	"from_state"	"from_zip"	"from_country"
                        "to_loccode"	"to_city"	"to_state"	"to_zip"	"to_country"	scac	"service_mode"
                        "break_1_field"	"break_1_min"	"break_1_max"	"break_2_field"	"break_2_min"	"break_2_max"
                        "bate_field"	"rate_calc"	rate	"accessorial1_field"	"accessorial1_calc"	"accessorial1_rate"	"total_min"]

  belongs_to :user

  converter = lambda { |header| header.downcase }

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Rate.create!(row.to_hash)
    end
  end

  def self.load_rates(user)
    rates = [{
      contract_id: 'Knight Transportation TL CAR',
      lane_calc: 'CTRY-CTRY',
      scac: 'KNIG',
      mode: 'TL',
      service: 'Standard',
      from_loccode: '',
      from_city: '',
      from_state: '',
      from_zip: '',
      from_country: 'US',
      to_loccode: '',
      to_city: '',
      to_state: '',
      to_zip: '',
      to_country: 'US',
      rate_field: 'Mileage',
      rate_calc: 'Per',
      rate: '1.65',
      total_min: '520',
      total_max: '100000',
      break_1_field: '',
      break_1_min: '',
      break_1_max: '',
      break_2_field: '',
      break_2_min: '',
      break_2_max: ''
    },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '21.021',
               total_min: '700.7',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '20000',
               break_2_max: '48000'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '68.068',
               total_min: '68.07',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '0',
               break_2_max: '499'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '62.062',
               total_min: '85.09',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '500',
               break_2_max: '999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '52.052',
               total_min: '220.22',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '1000',
               break_2_max: '1999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '42.042',
               total_min: '350.35',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '2000',
               break_2_max: '4999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '38.038',
               total_min: '350.35',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '5000',
               break_2_max: '9999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '33.033',
               total_min: '350.35',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '0',
               break_1_max: '500',
               break_2_field: 'Weight',
               break_2_min: '10000',
               break_2_max: '19999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '22.022',
               total_min: '750.75',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '20000',
               break_2_max: '48000'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '70.07',
               total_min: '70.07',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '0',
               break_2_max: '499'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '65.065',
               total_min: '90.09',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '500',
               break_2_max: '999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '55.055',
               total_min: '240.24',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '1000',
               break_2_max: '1999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '45.045',
               total_min: '370.37',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '2000',
               break_2_max: '4999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '41.041',
               total_min: '370.37',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '5000',
               break_2_max: '9999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '36.036',
               total_min: '370.37',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '500.1',
               break_1_max: '1500',
               break_2_field: 'Weight',
               break_2_min: '10000',
               break_2_max: '19999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '24.024',
               total_min: '75.08',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '20000',
               break_2_max: '48000'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '72.072',
               total_min: '72.07',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '0',
               break_2_max: '499'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '68.068',
               total_min: '92.09',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '500',
               break_2_max: '999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '58.058',
               total_min: '255.26',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '1000',
               break_2_max: '1999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '48.048',
               total_min: '390.39',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '2000',
               break_2_max: '4999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '51.051',
               total_min: '390.39',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '5000',
               break_2_max: '9999'
             },
             {
               contract_id: 'Este LTL Car',
               lane_calc: 'CTRY-CTRY',
               scac: 'EXLA',
               mode: 'LTL',
               service: 'Standard',
               from_loccode: '',
               from_city: '',
               from_state: '',
               from_zip: '',
               from_country: 'US',
               to_loccode: '',
               to_city: '',
               to_state: '',
               to_zip: '',
               to_country: 'US',
               rate_field: 'Weight C',
               rate_calc: 'Per',
               rate: '38.038',
               total_min: '390.39',
               total_max: '100000',
               break_1_field: 'Mileage',
               break_1_min: '1500.1',
               break_1_max: '6000',
               break_2_field: 'Weight',
               break_2_min: '10000',
               break_2_max: '19999' 
             }]
    user.rates.create(rates)
  end

end
