module MercuryGateJson

  RATE_HEADERS = ['Contract Id', 'Lane Calc', 'From Loccode', 'From City', 'From State', 'From Zip', 'From Country',
                  'To Loccode', 'To City', 'To State', 'To Zip', 'To Country', 'SCAC', 'Service', 'Mode',
                  'Break 1 Field', 'Break 1 Min', 'Break 1 Max', 'Break 2 Field', 'Break 2 Min', 'Break 2 Max',
                  'Rate Field', 'Rate Calc', 'Rate', 'Accessorial1 Field', 'Accessorial1 Calc', 'Accessorial1 Rate',
                  'Total Min'].freeze

  def rate_table(user, enterprise)
=begin
    rates = user.rates.pluck(:contract_id, :lane_calc, :from_loccode, :from_city, :from_state, :from_zip,
                             :from_country, :to_loccode, :to_city, :to_state, :to_zip, :to_country, :scac,
                             :service, :mode, :break_1_field, :break_1_min, :break_1_max, :break_2_field,
                             :break_2_min, :break_2_max, :rate_field, :rate_calc, :rate, :accessorial1_field,
                             :accessorial1_calc, :accessorial1_rate, :total_min)
=end

    { authentication: { username: Profile.edge_pack_id(user), password: Profile.edge_pack_pwd(user) },
      script: "Edge.switchCompany('#{enterprise}');
                contract = Edge.getServerReport('Location', '#{Profile.pool_report(user)}', true);
                ship = Edge.getServerReport('Shipment', '#{Profile.mmo_shipment_report(user)}', true);
                contract = Edge.getServerReport('Contract', '#{Profile.contract_report(user)}', true);
                rate = Edge.openRateTableReport(contract);
                Edge.mojoExecute(ship, 'test', false);
                Edge.mojoCreateServerLoads(false)",
      inputReports: [
        {"name":"OptParam","type":"OptParam", headers:%w[Key Value],
         data: [["Allow Off-Duty Extension","false"],
                ["Backhaul Bias","Off"],
                ["CL Reference",""],
                ["CO2 Emissions Factor","22.37"],
                ["CO2 Factor Air","10.0"],
                ["CO2 Factor Intm Rail","238.0"],
                ["CO2 Factor LTL","80.0"],
                ["CO2 Factor Ocean","769.0"],
                ["CO2 Factor Rail","286.0"],
                ["CO2 Modes Air","Air?"],
                ["CO2 Modes Intm Rail","Intermodal?,IM?"],
                ["CO2 Modes LTL","LTL?"],
                ["CO2 Modes Ocean","Ocean?"],
                ["CO2 Modes Rail","Rail?"],
                ["Capacity Default","10.0"],
                ["Capacity Enforcement","Optimized Loads Only"],
                ["Capacity Strategy","Off"],
                ["Capacity Strategy (Secondary)","Off"],
                ["Carbon Tax","0.0"],
                ["Carrier Capacity Allocation","Allow Direct Over-Allocation"],
                ["Carrier Schedule Determination","Same as Location Hours"],
                ["Cluster Radius","80.0"],
                ["Cluster Radius Iter","0.0"],
                ["Cluster Radius Step","10.0"],
                ["Constraint Bias","Medium"],
                ["Constraint Bias Improvement","false"],
                ["Days of Operation","Mon - Sun"],
                ["Dest Location Restriction",""],
                ["Direct Rate Method","Least Cost"],
                ["Distance Determiner","Geo Only"],
                ["Distance Display","Miles"],
                ["Dock Capacity Default (Drop)","3"],
                ["Dock Capacity Default (Pickup)","3"],
                ["Dock Capacity Strategy","Off"],
                ["Dock Time Requirements","Full Service Time"],
                ["DockCapacityStrategyList","Off"],
                ["Driver Driving Limit","11.0"],
                ["Driver Duty Limit","14.0"],
                ["Driver Off-Duty Rest","10.0"],
                ["Drop Radius Carriers 1",""],
                ["Drop Radius Carriers 2",""],
                ["Drop Radius Ident 1","Off"],
                ["Drop Radius Ident 2","Off"],
                ["Drop Radius Limit 1","0.0"],
                ["Drop Radius Limit 2","0.0"],
                ["Duty Policy","Normal"],
                ["Earliest Actual Date","Use Normal Constraints"],
                ["Equipment Enforcement","false"],
                ["Extend Delivery Early","0.5"],
                ["Extend Delivery Late","0.0"],
                ["Extend Ship Early","0.0"],
                ["Extend Ship Late","0.5"],
                ["Fleet Capacity Strategy","Same as Non-Fleet"],
                ["Fleet Driver Schedules","Off"],
                ["Fleet Drivers","Off"],
                ["Fleet Locations","Off"],
                ["Fleet Vehicles","Off"],
                ["FleetDriverSchedulesList","Off"],
                ["FleetDriversList","Off"],
                ["FleetLocationsList","Off"],
                ["FleetVehiclesList","Off"],
                ["Fuel Index Adjustment","0.0"],
                ["Fuel Surcharge LTL","0.0"],
                ["Fuel Surcharge TL","0.0"],
                ["Future Iterations","3"],
                ["HOS / Speed Determination","Default Only"],
                ["Hours of Operation (Close)","22:00"],
                ["Hours of Operation (Open)","06:00"],
                ["Hours of Operation Enforcement","Arrival Time"],
                ["Hours of Operation Method","Default Only"],
                ["HoursOfOperationList","Default Only"],
                ["Input Date Adjustment","0.0"],
                ["International Stop Restrictions","None"],
                ["LTL Consolidation","false"],
                ["Load Carrier Contract",""],
                ["Load Drop Seq Num",""],
                ["Load Duty Limit","70.0"],
                ["Load Pickup Seq Num",""],
                ["Load Pref Restrictions","None"],
                ["Load Preference",""],
                ["Load Template Hybrids","Off"],
                ["Load Template Locations",""],
                ["Load Template Strategy","Off"],
                ["Load Templates",""],
                ["Max Out-Of-Route","1.2"],
                ["Max Out-Of-Route Iter","0.0"],
                ["Max Out-Of-Route Step","0.1"],
                ["Max Pool Hold Time","2.0"],
                ["Max Stops","5.0"],
                ["Max Stops Iter","0.0"],
                ["Max Stops Step","2.0"],
                ["Max Truck Cube","3500.0"],
                ["Max Truck Quantity","10000.0"],
                ["Max Truck Weight","45000.0"],
                ["Minimum Stop Size","0.0"],
                ["Non-Opt Rate Method","Assign Direct Rate"],
                ["Non-TL Consol Modes",""],
                ["Non-TL Transit Time Method","Same as Truckload"],
                ["Non-TL Weekend Exclusion Modes",""],
                ["Off-Duty Extension Max","84.0"],
                ["Origin Location Bias",""],
                ["Parallelism Bias","Default"],
                ["Param Version","3"],
                ["Pickup Radius Carriers 1",""],
                ["Pickup Radius Carriers 2",""],
                ["Pickup Radius Ident 1","Off"],
                ["Pickup Radius Ident 2","Off"],
                ["Pickup Radius Limit 1","0.0"],
                ["Pickup Radius Limit 2","0.0"],
                ["PivotAnalysisConfig",""],
                ["Pool Assignment",""],
                ["Pool Chains",""],
                ["Pool Consideration Iter","5.0"],
                ["Pool Date Policy",""],
                ["Pool Strategy","On"],
                ["Postliminary Depth","10"],
                ["Private Fleet SCAC",""],
                ["Private Fleet Strategy","Off"],
                ["RateTable","Rate Table"],
                ["Re-Rate Method","By Contract"],
                ["ReRateTable","(None)"],
                ["RouteMapConfig","40.0,-96.0,2.8E7,Orthographic"],
                ["STOCHAT Depth","2"],
                ["Savings Gambit Iter","4.0"],
                ["Savings Gambit Max","0.0"],
                ["Script Code",""],
                ["Script Engine","Off"],
                ["Service Time (Shipment)","15.0"],
                ["Service Time (Stop)","45.0"],
                ["Service Time (Unit Qty)","0.0"],
                ["Service Time Method","Default Only"],
                ["ServiceTimeList","Default Only"],
                ["Services Enforcement","false"],
                ["Shipment Type Compatibility Method","Exact Match"],
                ["Stop Restrictions","None"],
                ["Strategy","M-OOR"],
                ["Truckload Modes","TL,Truckload"],
                ["Vehicle Efficiency","5.0"],
                ["Vehicle Loading","LIFO"],
                ["Vehicle Speed","50.0"],
                ["VersionClient","3.32.2"],
                ["VersionServer","3.32"],
                ["altref",""],
                ["carjobid",""],
                ["carriercharge",""],
                ["carriercontract",""],
                ["class",""],
                ["cube","Cube"],
                ["daddr",""],
                ["dcity","Dest City"],
                ["dctry","Dest Ctry"],
                ["dgeo","Dest Geo"],
                ["dimensions_uom",""],
                ["dloccode","Dest Code"],
                ["dname","Dest Name"],
                ["dstate","Dest State"],
                ["dzip","Dest Zip"],
                ["edeliverdate","Target Delivery (Early)"],
                ["equipment",""],
                ["eshipdate","Target Ship (Early)"],
                ["height",""],
                ["historicalcharge",""],
                ["historicalcontract",""],
                ["itemclass",""],
                ["itemcube",""],
                ["itemid",""],
                ["itemquantity",""],
                ["itemtemperature_max",""],
                ["itemtemperature_min",""],
                ["itemuom",""],
                ["itemusernumeric1",""],
                ["itemusernumeric2",""],
                ["itemweight",""],
                ["ldeliverdate","Target Delivery (Late)"],
                ["length",""],
                ["loadingpriority",""],
                ["lshipdate","Target Ship (Late)"],
                ["mode",""],
                ["oaddr",""],
                ["ocity","Origin City"],
                ["octry","Origin Ctry"],
                ["ogeo","Origin Geo"],
                ["oloccode","Origin Code"],
                ["oname","Origin Name"],
                ["ostate","Origin State"],
                ["ozip","Origin Zip"],
                ["payment_terms",""],
                ["poolloc1",""],
                ["priref","Primary Reference"],
                ["quantity","Quantity"],
                ["rating_count",""],
                ["servicedays",""],
                ["services",""],
                ["shipopts",""],
                ["shiptype",""],
                ["temperature_max",""],
                ["temperature_min",""],
                ["usernumeric1",""],
                ["usernumeric2",""],
                ["weight","Weight"],
                ["weight_uom",""],
                ["width",""]
         ]
        }
      ]
    }

  end

  def auth_mmo(user)

    "{ authentication: { username: #{Profile.edge_pack_id(user)}, password: #{Profile.edge_pack_pwd(user)} } }"

  end

end
